#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H
#define BTM_DEF_LOCAL_NAME "HD2"
#define BTA_DISABLE_DELAY 1000 /* in milliseconds */

#define BLE_INCLUDED FALSE
#define BTA_GATT_INCLUDED FALSE
#define SMP_INCLUDED FALSE
#endif
